### ISSUE TITLE
dockerfile don't work

### ISSUE THREAD

**Issue by SeriousShit** [snickers/snickers#167]
docker build failed with:
`
package context: unrecognized import path "context" (import path does not begin with hostname)
`

**Comment by flavioribeiro** [comment]
I merged @fsouza commit, can you try it again @SeriousShit? I'm aware that there are tons of improvements to be made on this docker deployment, snickers needs some [tlc](https://en.wikipedia.org/wiki/TLC), will try to reserve some time for it next week.

**Comment by fsouza** [comment]
@flavioribeiro I think you don't have automatic builds enabled on the snickers-docker image: https://hub.docker.com/r/flavioribeiro/snickers-docker/tags/ x)

You'll have to build it locally and push to Docker Hub, then update the Dockerfile on this repository.

**Comment by SeriousShit** [comment]
@flavioribeiro The problem still occurs. Regarded whether I try it with docker or the makefile.

It seems to be a probelm with the dependencies. If I replace aws-sdk-go and grab manually with old versions, the makefile works.

**Comment by kslimani** [comment]
@flavioribeiro : i think @SeriousShit is correct. the downloader `http.go` is using the old grab api (ie: the method `grab.GetAsync` is undefined in current grab library master branch.

I suggest trying something like replacing `"github.com/cavaliercoder/grab"` by `"gopkg.in/cavaliercoder/grab.v1"` [here](https://github.com/snickers/snickers/blob/master/downloaders/http.go#L8). (_i have no knowledge in Go language, so better check if it is correct_).

**Comment by kslimani** [comment]
Oh, and i think there si also a problem with snikers/hls : i think the build for libsegmenter.so is ok, but it seems theere is a path problem to the lib as it fail with the folowing error : `cannot find -lsegmenter`.

A "fast and dirty" workaround was to copy libsegmenter.so in /usr/local/lib folder. (but i am not sure this is the proper way to fix).
